/**
  Created by JamesChang
  Date/檔案建立日期: 2020/4/5
  Time/檔案建立時間: 上午 08:18
  File Description/檔案描述:
**/

CREATE TABLE `BS_ROLE` (
	`UUID` BINARY(16) COMMENT 'ID'
	, `VERSION` INT DEFAULT 0 COMMENT '版本，每修改一次就是加1'
	, `ISSURE` INT DEFAULT 2 COMMENT '0：刪除、1：新增中、2：使用中'
	, `NOTES` VARCHAR(100) COMMENT '資料註記'
	, `DATE_CREATED` TIMESTAMP NOT NULL COMMENT '資料建立時間'
	, `MAN_CREATED` VARCHAR(20) NOT NULL COMMENT '資料建立者'
	, `LAST_UPDATED` TIMESTAMP COMMENT '資料更新時間'
	, `MAN_LAST_UPDATED` VARCHAR(20) COMMENT '資料更新者'
	, `AUTHORITY` VARCHAR(100) COMMENT '權限'
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '系統角色' ;
INSERT INTO BS_ROLE (UUID,DATE_CREATED,MAN_CREATED,AUTHORITY) VALUES (UUID_TO_BIN(UUID()),CURRENT_TIMESTAMP,'FWJDBA','ROLE_ADMIN');
INSERT INTO BS_ROLE (UUID,DATE_CREATED,MAN_CREATED,AUTHORITY) VALUES (UUID_TO_BIN(UUID()),CURRENT_TIMESTAMP,'FWJDBA','ROLE_USER');


CREATE TABLE `BS_USER` (
	`UUID` BINARY(16)
	, `VERSION` INT DEFAULT 0 COMMENT '版本，每修改一次就是加1'
	, `ISSURE` INT DEFAULT 2 COMMENT '0：刪除、1：新增中、2：使用中'
	, `NOTES` VARCHAR(100) COMMENT '資料註記'
	, `DATE_CREATED` TIMESTAMP NOT NULL COMMENT '資料建立時間'
	, `MAN_CREATED` VARCHAR(20) NOT NULL COMMENT '資料建立者'
	, `LAST_UPDATED` TIMESTAMP COMMENT '資料更新時間'
	, `MAN_LAST_UPDATED` VARCHAR(20) COMMENT '資料更新者'
	, `USERNAME` VARCHAR(20) COMMENT '使用者帳號'
	, `PASSWORD` VARCHAR(200) COMMENT '使用者密碼'
	, `FULLNAME` VARCHAR(20) COMMENT '使用者名稱'
	, `ENABLED` INT DEFAULT 1 COMMENT '可以登入'
	, `ACCOUNTEXPIRED` INT DEFAULT 0 COMMENT '帳戶已逾期'
	, `ACCOUNTLOCKED` INT DEFAULT 0 COMMENT '帳戶已被鎖定'
	, `PASSWORDEXPIRED` INT DEFAULT 1 COMMENT '需要輸入密碼'
) ENGINE = InnoDB DEFAULT CHARSET = utf8 ;

CREATE TABLE `BS_USER_ROLE` (
	`UUID` BINARY(16) COMMENT 'ID'
	, `VERSION` INT DEFAULT 0 COMMENT '版本，每修改一次就是加1'
	, `ISSURE` INT DEFAULT 2 COMMENT '0：刪除、1：新增中、2：使用中'
	, `NOTES` VARCHAR(100) COMMENT '資料註記'
	, `DATE_CREATED` TIMESTAMP NOT NULL COMMENT '資料建立時間'
	, `MAN_CREATED` VARCHAR(20) NOT NULL COMMENT '資料建立者'
	, `LAST_UPDATED` TIMESTAMP COMMENT '資料更新時間'
	, `MAN_LAST_UPDATED` VARCHAR(20) COMMENT '資料更新者'
	, `BS_USER_ID` BINARY(16) COMMENT 'USER_ID'
	, `BS_ROLE_ID` BINARY(16) COMMENT 'ROLE_ID'
) ENGINE = INNODB DEFAULT CHARSET = UTF8 ;