/**
  Created by JamesChang
  Date/檔案建立日期: 2020/3/29
  Time/檔案建立時間: 下午 12:35
  File Description/檔案描述: 家庭支出系統
**/

CREATE TABLE `MS100`  (
 `UUID` BINARY(16) COMMENT 'UUIDTOBIN(UUID())' ,
 `VERSION` INT DEFAULT 0 COMMENT '版本，每修改一次就是加1' ,
 `ISSURE` INT DEFAULT 2 COMMENT '0：刪除、1：新增中、2：使用中' ,
 `NOTES` VARCHAR(100) COMMENT '資料註記' ,
 `DATE_CREATED` TIMESTAMP NOT NULL COMMENT '資料建立時間' ,
 `MAN_CREATED` VARCHAR(20) NOT NULL COMMENT '資料建立者' ,
 `LAST_UPDATED` TIMESTAMP COMMENT '資料更新時間' ,
 `MAN_LAST_UPDATED` VARCHAR(20) COMMENT '資料更新者' ,
 `STATUS` BIGINT COMMENT '帳本類別,BS101.MS100_STATUS' ,
 `OWNER_NAME` VARCHAR(20) COMMENT '擁有者_姓名' ,
 `ACCOUNT_NAME` VARCHAR(50) COMMENT '帳戶中文名稱' ,
 `ACCOUNT_NO` VARCHAR(20) COMMENT '帳號' ,
 `BANK_NO` VARCHAR(5) COMMENT '銀行代碼'
) ENGINE=InnoDB DEFAULT CHARSET=utf8   COMMENT = '帳本' ;

CREATE TABLE `MS101`  (
 `UUID` BINARY(16) ,
 `VERSION` INT DEFAULT 0 COMMENT '版本，每修改一次就是加1' ,
 `ISSURE` INT DEFAULT 2 COMMENT '0：刪除、1：新增中、2：使用中' ,
 `NOTES` VARCHAR(100) COMMENT '資料註記' ,
 `DATE_CREATED` TIMESTAMP NOT NULL COMMENT '資料建立時間' ,
 `MAN_CREATED` VARCHAR(20) NOT NULL COMMENT '資料建立者' ,
 `LAST_UPDATED` TIMESTAMP COMMENT '資料更新時間' ,
 `MAN_LAST_UPDATED` VARCHAR(20) COMMENT '資料更新者' ,
 `MS100_ID` BINARY(16) NOT NULL COMMENT '歸屬帳本' ,
 `STATUS1` BIGINT NOT NULL COMMENT '收入或支出，BS101.MS101_STATUS1' ,
 `STATUS2` BIGINT COMMENT '金額類別，BS101.MS101_STATUS2' ,
 `AMT` INT NOT NULL COMMENT '金額' ,
 `REMARK` VARCHAR(500) COMMENT '備註'
) ENGINE=InnoDB DEFAULT CHARSET=utf8   COMMENT = '收支資料' ;


CREATE TABLE `ms101` (
 `UUID` binary(16) DEFAULT NULL,
 `VERSION` int(11) DEFAULT 0 COMMENT '版本，每修改一次就是加1',
 `ISSURE` int(11) DEFAULT 2 COMMENT '0：刪除、1：新增中、2：使用中',
 `NOTES` varchar(100) DEFAULT NULL COMMENT '資料註記',
 `DATE_CREATED` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '資料建立時間',
 `MAN_CREATED` varchar(20) NOT NULL COMMENT '資料建立者',
 `LAST_UPDATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '資料更新時間',
 `MAN_LAST_UPDATED` varchar(20) DEFAULT NULL COMMENT '資料更新者',
 `MS100_ID` binary(16) NOT NULL COMMENT '歸屬帳本',
 `STATUS1` bigint(20) NOT NULL COMMENT '收入或支出，BS101.MS101_STATUS1',
 `STATUS2` bigint(20) DEFAULT NULL COMMENT '金額類別，BS101.MS101_STATUS2',
 `AMT` int(11) NOT NULL COMMENT '金額',
 `REMARK` varchar(500) DEFAULT NULL COMMENT '備註',
 `HAPPEN_DATE` datetime DEFAULT NULL COMMENT '收支日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='收支資料';