/**
  Created by JamesChang
  Date/檔案建立日期: 2020/2/1
  Time/檔案建立時間: 下午 02:53
  File Description/檔案描述: 系統程式選單
 */
INSERT INTO APP_LIST (APP_NAME,APP_CNAME,IDX,ACTION_TYPE,SHOW_ON_MENU,UUID,VERSION,NOTES,ISSURE,STATUS,DATE_CREATED,MAN_CREATED,MAN_LAST_UPDATED,LAST_UPDATED) VALUES ('system','系統設定',0,'isDropdown',1,UUID_TO_BIN(UUID()),0,'30',2,'5',CURRENT_TIMESTAMP(),'系統管理員','系統管理員',CURRENT_TIMESTAMP());
INSERT INTO APP_LIST (APP_NAME,PARENT_APP,APP_CNAME,IDX,ACTION_TYPE,CONTROLLER,ACTION,SHOW_ON_MENU,UUID,VERSION,NOTES,ISSURE,STATUS,DATE_CREATED,MAN_CREATED,MAN_LAST_UPDATED,LAST_UPDATED) VALUES ('bsAppList','system','系統程式選單',100,'onlyFunction','bs','bsAppList',1,UUID_TO_BIN(UUID()),0,'30',2,'5',CURRENT_TIMESTAMP(),'系統管理員','系統管理員',CURRENT_TIMESTAMP());
INSERT INTO APP_LIST (APP_NAME,APP_CNAME,IDX,ACTION_TYPE,SHOW_ON_MENU,UUID,VERSION,NOTES,ISSURE,STATUS,DATE_CREATED,MAN_CREATED,MAN_LAST_UPDATED,LAST_UPDATED) VALUES ('example','系統CRUD範例',0,'isDropdown',1,UUID_TO_BIN(UUID()),0,'30',2,'5',CURRENT_TIMESTAMP(),'系統管理員','系統管理員',CURRENT_TIMESTAMP());
INSERT INTO APP_LIST (APP_NAME,PARENT_APP,APP_CNAME,IDX,ACTION_TYPE,CONTROLLER,ACTION,SHOW_ON_MENU,UUID,VERSION,NOTES,ISSURE,STATUS,DATE_CREATED,MAN_CREATED,MAN_LAST_UPDATED,LAST_UPDATED) VALUES ('ex100','example','EX100',100,'onlyFunction','ex100','index',1,UUID_TO_BIN(UUID()),0,'30',2,'5',CURRENT_TIMESTAMP(),'系統管理員','系統管理員',CURRENT_TIMESTAMP());